{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.ysj001",
    "module": "bytecodeutil-plugin",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "mpiklnzgzfbardxzy5nt2dfvua"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "bytecodeutil-plugin-1.0.0-SNAPSHOT.jar",
          "url": "bytecodeutil-plugin-1.0.0-SNAPSHOT.jar",
          "size": 64633,
          "sha512": "9fbf5b84a787b9e500eabd63a1b9cebb865e1266eb2fae1741a1fc92dcb3355afc477b9b9fe543373a251fe9bf3d8134d92790b3742f602bfbc608b3f8c37e74",
          "sha256": "999b5636b515784e403c7178998076cbbeb4e7448c60b486a4a9ae03ea3ff4b5",
          "sha1": "c8d6a15f13e2de9c748116718f485c03ff0b1367",
          "md5": "bcf842c55eaba4b0e45474c158abe3fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.ysj001",
          "module": "bytecodeutil-api",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "bytecodeutil-plugin-1.0.0-SNAPSHOT.jar",
          "url": "bytecodeutil-plugin-1.0.0-SNAPSHOT.jar",
          "size": 64633,
          "sha512": "9fbf5b84a787b9e500eabd63a1b9cebb865e1266eb2fae1741a1fc92dcb3355afc477b9b9fe543373a251fe9bf3d8134d92790b3742f602bfbc608b3f8c37e74",
          "sha256": "999b5636b515784e403c7178998076cbbeb4e7448c60b486a4a9ae03ea3ff4b5",
          "sha1": "c8d6a15f13e2de9c748116718f485c03ff0b1367",
          "md5": "bcf842c55eaba4b0e45474c158abe3fe"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bytecodeutil-plugin-1.0.0-SNAPSHOT-javadoc.jar",
          "url": "bytecodeutil-plugin-1.0.0-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "98903b4456272a7a72e3badeadbc21e32604c230a6c0f579670304e47c342088f7c757d23371d52519d47e645f2cca5b571d18257f2e4377b06be057ea98af67",
          "sha256": "29db2742993faf4086c275f3b9e0b352ca87d002edb9556991b63cd7937c46a9",
          "sha1": "d0551b379b2f06eb6d0cb0444b2f60faa6110ad9",
          "md5": "895c365be1068f10cecb60fc29d2720e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bytecodeutil-plugin-1.0.0-SNAPSHOT-sources.jar",
          "url": "bytecodeutil-plugin-1.0.0-SNAPSHOT-sources.jar",
          "size": 18906,
          "sha512": "f8cbd67c3f31936b14539660d66febcc28166252c20584fb41f18c5daae8d4d2d3107eebb469466909f5e6f4006280b42f3d66468af87d378fa0085a6c896441",
          "sha256": "0582269274d0698c417ad253a986bfcdc412c656236a6e22b618a91362fdc3ea",
          "sha1": "f795d5e725a597f3e0a776d54347eddcb6b7ff64",
          "md5": "3710408a14ccc6e1ccc7010149b12948"
        }
      ]
    }
  ]
}
