{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.ysj001",
    "module": "bytecodeutil-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "zg6f3gvrcjew5iorsfbonw55wy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "bytecodeutil-plugin-1.0.0.jar",
          "url": "bytecodeutil-plugin-1.0.0.jar",
          "size": 64682,
          "sha512": "110ab8016db455f337101fe8db269008cd1680ccd82d17c3ba68118c728ba5e8de111939b6fae6d31930981c7c024943152bf87e4fcc3c651a07135ae6feeeef",
          "sha256": "0159c90dc8d8c0d86a4c806e0bfc3290760e24af568ec8a4df0524bf0e912c8a",
          "sha1": "3041e59e1bbb68bfa7a3a33ce72e039e1e6b9fd8",
          "md5": "9c66f49c0c87b0b47d7398c30dd76418"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.ysj001",
          "module": "bytecodeutil-api",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "bytecodeutil-plugin-1.0.0.jar",
          "url": "bytecodeutil-plugin-1.0.0.jar",
          "size": 64682,
          "sha512": "110ab8016db455f337101fe8db269008cd1680ccd82d17c3ba68118c728ba5e8de111939b6fae6d31930981c7c024943152bf87e4fcc3c651a07135ae6feeeef",
          "sha256": "0159c90dc8d8c0d86a4c806e0bfc3290760e24af568ec8a4df0524bf0e912c8a",
          "sha1": "3041e59e1bbb68bfa7a3a33ce72e039e1e6b9fd8",
          "md5": "9c66f49c0c87b0b47d7398c30dd76418"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bytecodeutil-plugin-1.0.0-javadoc.jar",
          "url": "bytecodeutil-plugin-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "7464b0dd7d0083cfd45718859d25e7a3ea11c2a22b0df8c247c5f94bb2654ccb1ccb817bfb57570fd4de1a1d6f0a2ac8465b54f7fb89296500b1684450679537",
          "sha256": "11c77c99ddba2fe8598d03253b3217a519234be7fb03955c748d50f1dd01aed2",
          "sha1": "7d9875655fe0e79a338f9f1cbc70fdb2024aef60",
          "md5": "5d75b50f2e6512a4304c79dc87c3c6b5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bytecodeutil-plugin-1.0.0-sources.jar",
          "url": "bytecodeutil-plugin-1.0.0-sources.jar",
          "size": 18923,
          "sha512": "6b297f071c0ed400f3bd9e63dadb23f1930f22069be82bbf9d40defa44f3651e2fcb6d4539d86c688af50aea8fdc2723955cce4b757c45684051518655434d1b",
          "sha256": "c3d81ef1b9c6d033557c725f3f9b3e427fa42b7cfa5982446faf4c45d8c60d86",
          "sha1": "f52747c0b36397b8af70c5462ca1567c3c0165af",
          "md5": "a00eb812fae8be14d2d2bdc9ff0c14ed"
        }
      ]
    }
  ]
}
